In [1]:
from engine.agent import Human, RandomAgent, MCTSAgent
import numpy as np
from engine.board import Board
from engine.env import Env
from sim import play

game_env = Env()

player1 = MCTSAgent(game_env=game_env, player_to_move=1, search_depth=1000)
player2 = Human(game_env=game_env, player_to_move=-1)

p1 = 0
p2 = 0
d = 0
for i in range(1):
    result = play(player1=player1, player2=player2, game_env=game_env, display=True)
    game_env.reset()
    if result == 1: p1 += result
    elif result == -1: p2 += -result
    else: d += (result+1)
    print('games played: ', i)


print(f'simulation results:         player1 win: {p1}          player2 win: {p2}       draw: {d}')

now it is turn for player:  1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
now it is turn for player:  -1
child 0 === player to move: 1 === parent action: 6 === ucb: -0.07504385555338816 === visits: 114 === score: 47.56929473611463
child 1 === player to move: 1 === parent action: 5 === ucb: -0.07247530424685555 === visits: 191 === score: 58.803793085821866
child 2 === player to move: 1 === parent action: 4 === ucb: -0.0755251702242008 === visits: 130 === score: 50.115297304608724
child 3 === player to move: 1 === parent action: 3 === ucb: -0.08822673669285258 === visits: 319 === score: 65.74015179974992
child 4 === player to move: 1 === parent action: 2 === ucb: -0.06865233621962435 === visits: 143 === score: 53.04157384513593
child 5 === player to move: 1 === parent action: 1 === ucb: -0.07993348151376312 === visits: 53 === score: 34.031581598996326
child 6 === player to move: 1 === parent action: 0 === ucb: -0.0799171393652623

KeyboardInterrupt: Interrupted by user